# pod.yaml template file that creates pod
kind: Pod
apiVersion: v1
metadata:
    name: abctechnologies-pod
    namespace: default
    labels:
        role: abc-tech-app
spec:
    containers:
        - image: peteoguocha/abctechnologies:docker_tag
          name: app


